### ISSUE TITLE
Support Lora or other peft

### ISSUE THREAD

**Issue by 2033329616** [FlagOpen/FlagScale#1]
Do model parallelism and pipeline parallelism support efficient fine-tuning methods such as Lora

**Comment by aoyulong** [comment]
Flagscale only support the fine-tuning for all parameters for now, but we plan to incorporate the LoRA. Could you please provide more detailed requirements so that we can take them into consideration for the future implementation?

**Comment by 2033329616** [comment]
PEFT includes various fine-tuning methods, such as Lora, which is better if the project is compatible with PEFT

**Comment by aoyulong** [comment]
That is a great suggestion, and we will work to integrate PEFT effectively.
