### ISSUE TITLE
[QUESTION] Support other hardware?

### ISSUE THREAD

**Issue by SueeH** [FlagOpen/FlagScale#16]
By now, FlagScale wupport training on chinese domestic hardwares, including Iluvatar CoreX and Baidu KUNLUN chips.
Any other hardwares will be supported in future？

**Comment by aoyulong** [comment]
@SueeH We will collaborate with manufacturers to support more hardwares. Soon, FlagScale will provide support for chips such as Moore Threads, Huawei Ascend and other hardwares.
