### ISSUE TITLE
异构训练问题

### ISSUE THREAD

**Issue by derekwin** [FlagOpen/FlagScale#179]
请问现在支持寒武纪和海光的芯片吗？以及异构通信库在哪里下载？有无源码提供。

**Comment by aoyulong** [comment]
Just a heads up that FlagScale is not yet set up for heterogeneous training on these two chips, and the communication library is also not open-sourced. We are working on adding these features soon, so keep an eye out for updates!

**Comment by derekwin** [comment]
> Just a heads up that FlagScale is not yet set up for heterogeneous training on these two chips, and the communication library is also not open-sourced. We are working on adding these features soon, so keep an eye out for updates!

ok, thank you.
