### ISSUE TITLE
异构训练报NCCL错误

### ISSUE THREAD

**Issue by echo-valor** [FlagOpen/FlagScale#201]
![image](https://github.com/user-attachments/assets/30e90642-6fbe-491d-a17f-632f8b8074cb)

使用一台8卡的A100和一台8卡的H800进行训练，hetero=pipline-stages为1 16 1 16，tp=2，pp=2，报如下错误：

![image](https://github.com/user-attachments/assets/dfaf129e-7dbd-496b-81bf-44ad6c2c6d7f)

环境肯定是没问题的，从0开始训练时可以跑通，求助是否因为异构参数设置影响？感谢

**Comment by aoyulong** [comment]
@heavyrain-lzy 请帮忙看看 @echo-valor 的问题哈。

**Comment by aoyulong** [comment]
> ![image](https://private-user-images.githubusercontent.com/28260618/363104042-30e90642-6fbe-491d-a17f-632f8b8074cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNTkwMDksIm5iZiI6MTcyNTE1ODcwOSwicGF0aCI6Ii8yODI2MDYxOC8zNjMxMDQwNDItMzBlOTA2NDItNmZiZS00OTFkLWExN2YtNjMyZjhiODA3NGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAyNDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNjEzNmY1NTVlZTE4NDBmYWI0NjA5YTkwYzBlOGJkOGQ2ZmU5NDg5M2Y2ZjIzMTMwMTAyNzk2ODIzNjI1MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HcF3ei-KsCtkCBHT5ohuDh92RYpB9mbvWbNObvYhT2k)
> 
> 使用一台8卡的A100和一台8卡的H800进行训练，hetero=pipline-stages为1 16 1 16，tp=2，pp=2，报如下错误：
> 
> ![image](https://private-user-images.githubusercontent.com/28260618/363104513-dfaf129e-7dbd-496b-81bf-44ad6c2c6d7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNTkwMDksIm5iZiI6MTcyNTE1ODcwOSwicGF0aCI6Ii8yODI2MDYxOC8zNjMxMDQ1MTMtZGZhZjEyOWUtN2RiZC00OTZiLTgxYmYtNDRhZDZjMmM2ZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAyNDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZjg5OTdlYjkyZDFhMDZkNDk5ZmUyNDAxOTFiODhjNDA5MWVhOWY5NjA1MjUzN2FiZjM3MGM3Y2NhMjYzMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ISiWlZUd2MnjZA9t-S938QbRd1u6a4i3xFKmWGIubSg)
> 
> 环境肯定是没问题的，从0开始训练时可以跑通，求助是否因为异构参数设置影响？感谢

能否给出具体使用的FlagScale版本和关于NCCL相关的配置。
