### ISSUE TITLE
[Env] When running LLaVa, the versions installed using pip are not compatible

### ISSUE THREAD

**Issue by Bowen12992** [FlagOpen/FlagScale#259]
# Problem Description

I am running LLaVa in [FlagScale](https://github.com/FlagOpen/FlagScale) with cmd：
`python run.py --config-path ./examples/llava_onevision/conf --config-name config action=run` 
but I got several python package dependencies missing, such as `apex`, `transformer-engine-github` & `flash-attn`

# Env
For some reasons, I cannot use official docker images, or just might as well say that i am a non-docker user.
Before running the LLaVa model on  a 8-card NV A100 machine,  I have run：

```bash
pip install -r magatron/requirements-cuda.txt
pip install -r vllm/requirements-cuda.txt
pip install -r flagscale/requirements-common.txt
```
and installed all the requirements files in FlagScale, but i still got python package dependencies missing.

# what I tried

I tried to install various missing packages, but there were some incompatibility issues such as：

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/d1c11ee4-49c3-4915-ba93-05f29fe510c7">

<img width="683" alt="image" src="https://github.com/user-attachments/assets/38876711-2e03-451d-bc26-6f852374624d">

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/ca9541e8-07c4-47f2-a59a-c3933a1f8588">

so i tried to install them from src：

```
# apex
git clone https://gitee.com/aoyulong/apex-github
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./

# transformer-engine
git clone https://gitee.com/aoyulong/transformer-engine-github.git
git checkout stable stable  # bug in stable !!!  use release_v1.11
git submodule update --init --recursive
pip install -v .

# flash-attn
git clone https://gitee.com/aoyulong/flash-attention-github
git submodule update --init --recursive
python setup.py install
```
it took really a long time to compile and another error occurs with `transformer-engine`：
<img width="955" alt="image" src="https://github.com/user-attachments/assets/982b9301-987c-45f5-889e-f0694fdc276a">
which is descriped in https://github.com/NVIDIA/TransformerEngine/issues/1236

So I hope FlagScale can add all the python package version into the requirement list for non-docker users.

**Comment by aoyulong** [comment]
At this time, installing from the source can be quite challenging. However, we are actively working on updating our build system to make this process smoother in the near future. Your patience is appreciated as we make these improvements!

**Comment by Bowen12992** [comment]
sure
