### ISSUE TITLE
flagscale参数定义问题

### ISSUE THREAD

**Issue by drakethree3** [FlagOpen/FlagScale#282]
请问一下flagscale的args参数定义在megaton下面megaton/training/arguments.py文件中，是如何在flagscale中调用的呢？另外，在train_aquila.py中库文件的导入好像是有问题的吧，是否应该是megaton.megaton.training呢？这个不影响训练吗？
![image](https://github.com/user-attachments/assets/d3a640ec-a9f4-4f30-bed7-a22ca53e185a)

**Comment by aoyulong** [comment]
@drakethree3 通过run.py启动任务，会自动生成启动脚本，里面会修改PYTHONPATH。比如：
`export PYTHONPATH=/path/to/FlagScale/megatron:/path/to/FlagScale`
