### ISSUE TITLE
[QUESTION] 支持在异构设备上进行训练吗？

### ISSUE THREAD

**Issue by slbqc** [FlagOpen/FlagScale#31]
你好，当前的FlagScale 支持在异构设备上训练吗？（Nvidia+昇腾）
如果不支持，未来是否考虑支持？

**Comment by aoyulong** [comment]
@slbqc 您好，FlagScale目前能支持兼容架构的不同设备上异构训练，对于NVIDIA+昇腾暂时还不支持，不过有相关规划。如果方便，能否提供更多的需求场景信息，这将有助于我们安排功能开发优先级。

**Comment by rookie-J** [comment]
> @slbqc 您好，FlagScale目前能支持兼容架构的不同设备上异构训练，对于NVIDIA+昇腾暂时还不支持，不过有相关规划。如果方便，能否提供更多的需求场景信息，这将有助于我们安排功能开发优先级。

请问兼容架构是指cuda和类cuda架构吗，比如NVIDIA+海光DCU这种支持吗

**Comment by aoyulong** [comment]
@rookie-J 是的，真正异构训练起来还需要对应厂商通信库进行兼容适配。
